// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/project1": {
    params: {};
  };
  "/project2": {
    params: {};
  };
  "/project3": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/project1" | "/project2" | "/project3";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/project1.tsx": {
    id: "routes/project1";
    page: "/project1";
  };
  "routes/project2.tsx": {
    id: "routes/project2";
    page: "/project2";
  };
  "routes/project3.tsx": {
    id: "routes/project3";
    page: "/project3";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/project1": typeof import("./app/routes/project1.tsx");
  "routes/project2": typeof import("./app/routes/project2.tsx");
  "routes/project3": typeof import("./app/routes/project3.tsx");
};